### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by imnew827** [nickmartin1ee7/Uwuify.DiscordBot#17]
doesnt create application cmds in my server even tho i have admin perms

**Comment by nickmartin1ee7** [comment]
> The propagation period is 1 hour for new or edited slash commands. 

If you need instant propagation, you can use the `DebugServerId` in the [DiscordSettings](https://github.com/nickmartin1ee7/Uwuify.DiscordBot/blob/main/Uwuify.DiscordBot.WorkerService/Models/DiscordSettings.cs) class by adding that section in the AppSettings or Docker Compose.

Additionally, your invite needs to be suffixed with `&permissions=0&scope=bot%20applications.commands`
